-- NYC Restaurant Intelligence Platform — database schema
-- Generated by notebooks/04_database_schema.ipynb
-- Target: PostgreSQL (Supabase)

-- Order matters: referenced tables must exist before the tables that point at them.
drop table if exists violations cascade;
drop table if exists inspections cascade;
drop table if exists restaurants cascade;
drop table if exists violation_codes cascade;
drop table if exists neighborhoods cascade;

-- ---------- reference tables ----------

create table neighborhoods (
    nta_code         text primary key,
    nta_name         text not null,
    borough          text not null,
    population_2010  integer
);

create table violation_codes (
    violation_id           integer primary key,
    violation_code         text not null,
    violation_description  text
);

-- ---------- restaurants ----------

create table restaurants (
    camis             text primary key,
    dba               text,
    boro              text,
    building          text,
    street            text,
    zipcode           text,
    phone             text,
    cuisine           text,
    latitude          double precision,
    longitude         double precision,
    nta_code          text references neighborhoods (nta_code),
    community_board   text,
    council_district  text,
    never_inspected   boolean,
    n_inspections     integer,
    first_inspection  date,
    last_inspection   date,
    avg_score         numeric(6, 2),
    latest_score      numeric(6, 2),
    latest_grade      text,
    total_violations  integer,
    total_critical    integer,
    ever_closed       boolean
);

-- ---------- inspections ----------

create table inspections (
    inspection_id        integer primary key,
    camis                text not null references restaurants (camis),
    inspection_date      date not null,
    inspection_type      text,
    inspection_category  text,
    inspection_stage     text,
    score                numeric(6, 2),
    grade                text,
    grade_date           date,
    is_gradeable         boolean,
    n_violations         integer,
    n_critical           integer,
    closed_by_dohmh      boolean,
    action               text
);

-- ---------- violations ----------

create table violations (
    violation_row_id  integer primary key,
    inspection_id     integer not null references inspections (inspection_id),
    violation_id      integer not null references violation_codes (violation_id),
    is_critical       boolean
);

-- ---------- indexes ----------
-- Foreign keys are not indexed automatically in Postgres. Without these, every
-- join and every dashboard filter scans the whole table.

create index idx_restaurants_boro     on restaurants (boro);
create index idx_restaurants_cuisine  on restaurants (cuisine);
create index idx_restaurants_nta      on restaurants (nta_code);
create index idx_inspections_camis    on inspections (camis);
create index idx_inspections_date     on inspections (inspection_date);
create index idx_violations_insp      on violations (inspection_id);
create index idx_violations_code      on violations (violation_id);

-- ---------- access control ----------
-- Supabase exposes every table in the public schema over a REST API. Without row
-- level security, anyone holding the (publicly shipped) anon key could delete the
-- data. Enabling RLS denies everything by default; the policies below then grant
-- exactly one capability: anonymous reads. There is no insert, update or delete
-- policy, so the API cannot write at all.

alter table neighborhoods       enable row level security;
alter table violation_codes     enable row level security;
alter table restaurants         enable row level security;
alter table inspections         enable row level security;
alter table violations          enable row level security;

create policy "public read" on neighborhoods       for select to anon using (true);
create policy "public read" on violation_codes     for select to anon using (true);
create policy "public read" on restaurants         for select to anon using (true);
create policy "public read" on inspections         for select to anon using (true);
create policy "public read" on violations          for select to anon using (true);

-- RLS decides which ROWS a role may see. Table privileges decide whether the role
-- may touch the table at all, and the two are independent — a table with a
-- permissive policy but no grant is still invisible to the API. Granting select
-- and nothing else means the anon role can read every row and modify none.
grant usage on schema public to anon;
grant select on all tables in schema public to anon;
